insurance <- read.csv('~/ml/Chapter 06/insurance.csv', stringsAsFactors = T)
str(insurance)
insurance$bmi30 <- ifelse( insurance$bmi >= 30, 1, 0)
insurance$age2 <- insurance$age^2
ins_model2 <- lm(expenses ~ age + age2 + children  + bmi + sex + bmi30*smoker + region, data = insurance)
summary(ins_model2)
summary(ins_model)
lm(insurance$expenses insurance$bmi30*insurance$smoker)
lm(insurance$expenses ~ insurance$bmi30*insurance$smoker)
summary(lm(insurance$expenses ~ insurance$bmi30*insurance$smoker))
